### ISSUE TITLE
Build errors with esp-idf instead of arduino framework

### ISSUE THREAD

**Issue by hjmcnew** [hjmcnew/esphome-hs2xx3a-custom-component#9]
When building with the arduino framework we see:
```
In file included from src/main.cpp:122:
src/leapmmw_sensor.h: In member function 'virtual void leapmmw::loop()':
src/leapmmw_sensor.h:167:28: warning: 'setled_state' may be used uninitialized in this function [-Wmaybe-uninitialized]
  167 |               publishSwitch("led", setled_state);
      |               ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~
```

When building with the esp-idf framework this is treated as an error:
```
In file included from src/main.cpp:107:
src/leapmmw_sensor.h: In member function 'virtual void leapmmw::loop()':
src/leapmmw_sensor.h:167:28: error: 'setled_state' may be used uninitialized in this function [-Werror=maybe-uninitialized]
               publishSwitch("led", setled_state);
               ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~
[...snip...]
cc1plus: some warnings being treated as errors
*** [/data/devtest/.pioenvs/devtest/src/main.o] Error 1
```

## Workaround
While this may break LED functionality comment out line 167 in the .h file.
### From
`publishSwitch("led", setled_state);`
### To
`// publishSwitch("led", setled_state);`

I haven't tested the workaround with real hardware because I don't have an esp-idf board with the sensor attached. Will work on getting that set up.

**Comment by crlogic** [comment]
I have an S2 (any ESP32) would work. But commenting out isn't really a workaround. And it was my understanding that IDF didn't support the included.h

So what am I missing here?

**Comment by hjmcnew** [comment]
For all I know this blows up when running on real hardware. :smile:
I've just confirmed that it will build correctly. I'm running on an 8266 with the arduino framework. I do have some esp32s that require the esp-idf framework though and could test on those over the next few days.

**Comment by crlogic** [comment]
Yeah I've tested the change to IDF. It complains about the .h which is the heart of the build.

**Comment by hjmcnew** [comment]
Sample yaml:
```
substitutions:
  device_name: devtest
  # This will vary based on your board
  uart_tx_pin: TX
  # This will vary based on your board
  uart_rx_pin: RX
  # This will vary based on your board
  gpio_pin: GPIO3
  # (Optional) Path to the leapmmw_sensor.h file relative to your esphome configuration directory.
  # header_file: leapmmw_sensor.h
packages:
  remote_package:
    url: https://github.com/hjmcnew/esphome-hs2xx3a-custom-component
    ref: release
    file: packages/leapmmw_sensor.yml

esp32:
  board: esp32dev
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_FREERTOS_UNICORE: y

# Enable logging
logger:
  hardware_uart: UART1
  baud_rate: 0


# Enable Home Assistant API
api:
  encryption:
    key: "<redacted>"

ota:
  password: "<redacted>"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Devtest Fallback Hotspot"
    password: "<redacted>"

# captive_portal:
```
[logs_devtest_compile_without_workaround.txt](https://github.com/hjmcnew/esphome-hs2xx3a-custom-component/files/9429365/logs_devtest_compile_without_workaround.txt)

[logs_devtest_compile_with_workaround.txt](https://github.com/hjmcnew/esphome-hs2xx3a-custom-component/files/9429357/logs_devtest_compile_with_workaround.txt)

**Comment by crlogic** [comment]
I'll give that a go tomorrow aft on my TinyS2

**Comment by hjmcnew** [comment]
A better work around is initializing the variable in the function. I gave it a whirl in #10. Builds cleanly with `framework: esp-idf` and `framework: arduino`.

**Comment by jamescadd** [comment]
This worked for me after incorporating the default led value in #10.  For the esp32-c3-devkitm-1 board it's currently necessary to include the platformio_options as follows:

```
esphome:
  name: "dfrobot-sen0395-1"
  platformio_options:
    board_build.f_flash: 40000000L
    board_build.flash_mode: dio
    board_build.flash_size: 4MB

esp32:
  variant: ESP32C3
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf
```
